### ISSUE TITLE
Names of inputs

### ISSUE THREAD

**Issue by mcwimm** [pymanga/pyMANGA#192]
@jbathmann @jvollhueter 
I just realized that some inputs could have the same names to make it easier to remember how they are defined (in the xml file).
E.g. in population Random and SimpleAsymmetricZOI we define the raster using *x_1*, *x_2* etc. and in FixedSalinity we use *x_min* and *x_max*.
Should we unify this? If so, which one do you prefer?

**Comment by jbathmann** [comment]
I think the meanings of the x_1 and x_min differ sligthly as one is used to define the grid whereas the other is used to describe a point (x,C(x)).
However, in general they could be unified. In that case i would vote for x_1 and x_2, y_1 and x_2 .....

**Comment by mcwimm** [comment]
adressed in issue #147
