### ISSUE TITLE
Webpage Developer Guide

### ISSUE THREAD

**Issue by mcwimm** [pymanga/pyMANGA#196]
Ongoing task... restructure and/or complete the developer guide

Developer Guide

- Getting Started (allgemeines bla, hier vllt. nochmal der Link zum download)
- Structure
- Style
- Workflow (PR, Benchmark, local preview of doxygen doc. ...)

**Comment by jbathmann** [comment]
- [ ] Getting started
- [X] Structure
- [x] Style
- [ ] Workflow
