### ISSUE TITLE
New structure

### ISSUE THREAD

**Issue by mcwimm** [pymanga/pyMANGA#219]
... divide TreeModelLib in PlantModelLib and ResourceLib with respective abstract classes (TreeModel becomes ResourceModel and PlantModel)

- [x] restructure libs (PR #220) 
- [x] update xml file
- [ ] update benchmark structure
- [x] update documentation structure - by the way: should we move this to an extra repo, too?
- [x] rewording
- [x] new names for Simple...

**Comment by jbathmann** [comment]
I think the change in the xml structure required changes in
1.) Project structure
2.) Project initialization

**Comment by mcwimm** [comment]
Methods that can go to ResourceModel.py
- makeGrid
- getParameters

Methods that can go to PlantModel.py
- extractRelevantInfomration (see PR #221 )
