### ISSUE TITLE
Support of python 3.7 will end in 06/23

### ISSUE THREAD

**Issue by mcwimm** [pymanga/pyMANGA#252]
![image](https://github.com/pymanga/pyMANGA/assets/48250781/2ce9948a-aae4-4bfc-a5d2-a07599d6925e)

I think the only reason why we still use py 3.7 is vtk/ogs. Can we remove this dependency for cases where ogs is not needed?

**Comment by jvollhueter** [comment]
Perhaps we should take a closer look at this in general. A version that works for whole pyMANGA would of course be best, and ideally this is the newest...

**Comment by rbnmj** [comment]
**pyMANGA seems to run with current versions of python and vtk:**  
*Tested with Win10, Python 3.11.1, OGS 6.4.0 and vtk 9.2.6.*  
<br>
- Non-OGS benchmarks are working.
- SimpleBettina/OGS_CI and OGSExampleSetup/OGS3D_SAZOI_BETTINA tested and working (with `<delta_t_ogs>604800</delta_t_ogs>`)
<br>
Console output for OGS_CI:  
![image](https://github.com/pymanga/pyMANGA/assets/122864139/2466be6a-7389-42fa-b939-946b34d9d598)
<br>
I am not sure how to assess if the results are correct but the simulation ran without error and the created files and time steps looked reasonable.

**Comment by mcwimm** [comment]
Great!
Tested it with Python 3.11.5, vtk 9.2.6, OGS 6.4.0 and it worked.
I also did not check the results but the problem before was, that it did not start the OGS calculation. So I assume it works.
